# Flair model

A simple notebook to:
- Read a pretrained Flair model
- Examples on how to do the task of generating text

In [1]:
from flair.embeddings import FlairEmbeddings
from flair.data import Sentence

import flair, torch
flair.device = torch.device('cpu') 

In [2]:
# --- INPUTS

# path2model can be set to:
#    "../histLM_dataset/flair/flair_1760_1900/best-lm.pt"
path2model = "../histLM_dataset/flair/flair_1760_1900/best-lm.pt"

In [3]:
# Read language model
language_model = FlairEmbeddings(path2model)

In [4]:
# Example sentence which has token [MASK]
mysent = "They were told that the [MASK] stopped working."

In [5]:
flair_sentence = Sentence(mysent)
language_model.embed(flair_sentence)

[Sentence: "They were told that the [ MASK ] stopped working ."   [− Tokens: 11]]

In [6]:
# now check out the embedded tokens.
for token in flair_sentence:
    print(token)
    print(token.embedding)

Token: 1 They
tensor([ 0.0051, -0.0005, -0.0168,  ...,  0.0135,  0.0080, -0.0082])
Token: 2 were
tensor([ 1.9208e-03, -8.2278e-05, -5.5975e-02,  ...,  1.7667e-02,
        -3.0257e-03, -5.0397e-04])
Token: 3 told
tensor([-4.2937e-02, -9.1127e-05, -4.2566e-02,  ..., -3.7135e-02,
         6.9754e-04, -2.6254e-03])
Token: 4 that
tensor([-6.7677e-02, -4.9359e-05, -1.6307e-03,  ..., -2.8282e-02,
         5.6025e-02,  1.3636e-04])
Token: 5 the
tensor([ 0.0031, -0.0019, -0.0213,  ..., -0.0202,  0.0213, -0.0004])
Token: 6 [
tensor([-0.0279, -0.0016, -0.0147,  ..., -0.0897, -0.0656,  0.0002])
Token: 7 MASK
tensor([-9.3989e-03, -3.7500e-05,  1.0471e-02,  ..., -3.1248e-02,
        -5.5736e-02,  5.0478e-04])
Token: 8 ]
tensor([ 7.2111e-03, -3.3496e-04, -9.4604e-03,  ..., -9.4257e-03,
        -6.6297e-02,  4.5420e-05])
Token: 9 stopped
tensor([-0.0025, -0.0114,  0.0026,  ...,  0.0273, -0.0259, -0.0019])
Token: 10 working
tensor([-0.0033,  0.0003, -0.0203,  ...,  0.0213,  0.1101,  0.0003])
Token: 11 

In [7]:
print(language_model.lm.generate_text("They were told that the engine stopped working ", 
                                      number_of_characters=500))

('They were told that the engine stopped working at a few hours but in striking accounts for having repaired to them the commander might send him to the capital .\nThe edge of the ravine a beautiful elevain obliterating known as mine Hist .\nHis eye-glass most inhabitants who frequent the shore of the Neva in the sea coast in the valleys which form the streams of Lucys hut are brooding as if they were gradually up birth .\nBefore me I have witnessed such a sudden flash of lightning and such a light on the star tower that it may not have long sinc', 18.13060546875)
